#!/usr/bin/env bash
set -e

echo "================================================"
echo " Debian Linux → Dev Environment (SAFE FINAL)"
echo "================================================"

# -----------------------------
# 0. Linux check
# -----------------------------
if [[ "$OSTYPE" != "linux-gnu"* ]]; then
  echo "ERROR: Linux only"
  exit 1
fi

# -----------------------------
# 1. System dependencies
# -----------------------------
echo "[1/6] Installing system dependencies..."
sudo apt update
sudo apt install -y \
  build-essential \
  curl \
  wget \
  file \
  git \
  procps \
  ca-certificates

# -----------------------------
# 2. Install Homebrew (Linuxbrew)
# -----------------------------
if ! command -v brew >/dev/null 2>&1; then
  echo "[2/6] Installing Homebrew (Linuxbrew)..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  echo "[2/6] Homebrew already installed"
fi

# -----------------------------
# 3. Rebuild ~/.profile safely
# -----------------------------
echo "[3/6] Configuring ~/.profile safely..."

if [ -f "$HOME/.profile" ]; then
  cp "$HOME/.profile" "$HOME/.profile.backup.$(date +%s)"
fi

cat > "$HOME/.profile" <<'EOF'
# ~/.profile — generated by install_dev_env_linux.sh

# === Homebrew (Linuxbrew) ===
if [ -d /home/linuxbrew/.linuxbrew/bin ]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

# === LLVM / Clang ===
export PATH="/home/linuxbrew/.linuxbrew/opt/llvm/bin:$PATH"

# === OpenJDK ===
export PATH="/home/linuxbrew/.linuxbrew/opt/openjdk/bin:$PATH"

# === Rust (cargo) ===
if [ -f "$HOME/.cargo/env" ]; then
  source "$HOME/.cargo/env"
fi

# === .NET ===
export DOTNET_ROOT="$HOME/.dotnet"
export PATH="$HOME/.dotnet:$PATH"
EOF

source "$HOME/.profile"

# -----------------------------
# 4. Update brew
# -----------------------------
echo "[4/6] Updating Homebrew..."
brew update

# -----------------------------
# 5. Install packages via brew
# -----------------------------
echo "[5/6] Installing brew packages..."

brew install \
  nano \
  vim \
  mc \
  net-tools \
  htop \
  btop \
  ctop \
  tmux \
  bat \
  ncdu \
  php \
  composer \
  node \
  openjdk \
  gcc \
  llvm \
  python \
  go \
  perl

# -----------------------------
# 6. Rust + .NET
# -----------------------------
echo "[6/6] Installing Rust and .NET..."

# Rust (rustup)
if ! command -v rustup >/dev/null 2>&1; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
fi
source "$HOME/.cargo/env"

# .NET 9
if ! command -v dotnet >/dev/null 2>&1; then
  wget -q https://dot.net/v1/dotnet-install.sh
  chmod +x dotnet-install.sh
  ./dotnet-install.sh --channel 9.0
  rm -f dotnet-install.sh
fi

source "$HOME/.profile"

# -----------------------------
# Version check
# -----------------------------
echo
echo "================================================"
echo " INSTALLED VERSIONS"
echo "================================================"

brew --version
echo

nano --version | head -n 1
vim --version | head -n 1
mc --version | head -n 1
htop --version
btop --version
tmux -V
bat --version
ncdu --version

echo
php -v | head -n 2
composer --version
node -v
npm -v
java --version
dotnet --version
gcc --version | head -n 1
clang --version | head -n 1
python3 --version
pip3 --version
go version
rustc --version
cargo --version
perl -v | head -n 2

echo
echo "================================================"
echo " DONE. Open a NEW terminal session."
echo "================================================"

